; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude LocalizeTableFeedback.msg.html

(cl:defclass <LocalizeTableFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LocalizeTableFeedback (<LocalizeTableFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalizeTableFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalizeTableFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<LocalizeTableFeedback> is deprecated: use billiards_msgs-msg:LocalizeTableFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalizeTableFeedback>) ostream)
  "Serializes a message object of type '<LocalizeTableFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalizeTableFeedback>) istream)
  "Deserializes a message object of type '<LocalizeTableFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalizeTableFeedback>)))
  "Returns string type for a message object of type '<LocalizeTableFeedback>"
  "billiards_msgs/LocalizeTableFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalizeTableFeedback)))
  "Returns string type for a message object of type 'LocalizeTableFeedback"
  "billiards_msgs/LocalizeTableFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalizeTableFeedback>)))
  "Returns md5sum for a message object of type '<LocalizeTableFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalizeTableFeedback)))
  "Returns md5sum for a message object of type 'LocalizeTableFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalizeTableFeedback>)))
  "Returns full string definition for message of type '<LocalizeTableFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalizeTableFeedback)))
  "Returns full string definition for message of type 'LocalizeTableFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalizeTableFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalizeTableFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalizeTableFeedback
))
