; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlaceBridgeResult.msg.html

(cl:defclass <PlaceBridgeResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlaceBridgeResult (<PlaceBridgeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceBridgeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceBridgeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlaceBridgeResult> is deprecated: use billiards_msgs-msg:PlaceBridgeResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceBridgeResult>) ostream)
  "Serializes a message object of type '<PlaceBridgeResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceBridgeResult>) istream)
  "Deserializes a message object of type '<PlaceBridgeResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceBridgeResult>)))
  "Returns string type for a message object of type '<PlaceBridgeResult>"
  "billiards_msgs/PlaceBridgeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceBridgeResult)))
  "Returns string type for a message object of type 'PlaceBridgeResult"
  "billiards_msgs/PlaceBridgeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceBridgeResult>)))
  "Returns md5sum for a message object of type '<PlaceBridgeResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceBridgeResult)))
  "Returns md5sum for a message object of type 'PlaceBridgeResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceBridgeResult>)))
  "Returns full string definition for message of type '<PlaceBridgeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceBridgeResult)))
  "Returns full string definition for message of type 'PlaceBridgeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceBridgeResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceBridgeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceBridgeResult
))
