; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlaceBridgeFeedback.msg.html

(cl:defclass <PlaceBridgeFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlaceBridgeFeedback (<PlaceBridgeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceBridgeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceBridgeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlaceBridgeFeedback> is deprecated: use billiards_msgs-msg:PlaceBridgeFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceBridgeFeedback>) ostream)
  "Serializes a message object of type '<PlaceBridgeFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceBridgeFeedback>) istream)
  "Deserializes a message object of type '<PlaceBridgeFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceBridgeFeedback>)))
  "Returns string type for a message object of type '<PlaceBridgeFeedback>"
  "billiards_msgs/PlaceBridgeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceBridgeFeedback)))
  "Returns string type for a message object of type 'PlaceBridgeFeedback"
  "billiards_msgs/PlaceBridgeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceBridgeFeedback>)))
  "Returns md5sum for a message object of type '<PlaceBridgeFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceBridgeFeedback)))
  "Returns md5sum for a message object of type 'PlaceBridgeFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceBridgeFeedback>)))
  "Returns full string definition for message of type '<PlaceBridgeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceBridgeFeedback)))
  "Returns full string definition for message of type 'PlaceBridgeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceBridgeFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceBridgeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceBridgeFeedback
))
