; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlanShotFeedback.msg.html

(cl:defclass <PlanShotFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlanShotFeedback (<PlanShotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanShotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanShotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlanShotFeedback> is deprecated: use billiards_msgs-msg:PlanShotFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanShotFeedback>) ostream)
  "Serializes a message object of type '<PlanShotFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanShotFeedback>) istream)
  "Deserializes a message object of type '<PlanShotFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanShotFeedback>)))
  "Returns string type for a message object of type '<PlanShotFeedback>"
  "billiards_msgs/PlanShotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanShotFeedback)))
  "Returns string type for a message object of type 'PlanShotFeedback"
  "billiards_msgs/PlanShotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanShotFeedback>)))
  "Returns md5sum for a message object of type '<PlanShotFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanShotFeedback)))
  "Returns md5sum for a message object of type 'PlanShotFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanShotFeedback>)))
  "Returns full string definition for message of type '<PlanShotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanShotFeedback)))
  "Returns full string definition for message of type 'PlanShotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanShotFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanShotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanShotFeedback
))
