; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlayResult.msg.html

(cl:defclass <PlayResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlayResult (<PlayResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlayResult> is deprecated: use billiards_msgs-msg:PlayResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayResult>) ostream)
  "Serializes a message object of type '<PlayResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayResult>) istream)
  "Deserializes a message object of type '<PlayResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayResult>)))
  "Returns string type for a message object of type '<PlayResult>"
  "billiards_msgs/PlayResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayResult)))
  "Returns string type for a message object of type 'PlayResult"
  "billiards_msgs/PlayResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayResult>)))
  "Returns md5sum for a message object of type '<PlayResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayResult)))
  "Returns md5sum for a message object of type 'PlayResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayResult>)))
  "Returns full string definition for message of type '<PlayResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayResult)))
  "Returns full string definition for message of type 'PlayResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayResult
))
