; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlayFeedback.msg.html

(cl:defclass <PlayFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlayFeedback (<PlayFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlayFeedback> is deprecated: use billiards_msgs-msg:PlayFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayFeedback>) ostream)
  "Serializes a message object of type '<PlayFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayFeedback>) istream)
  "Deserializes a message object of type '<PlayFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayFeedback>)))
  "Returns string type for a message object of type '<PlayFeedback>"
  "billiards_msgs/PlayFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayFeedback)))
  "Returns string type for a message object of type 'PlayFeedback"
  "billiards_msgs/PlayFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayFeedback>)))
  "Returns md5sum for a message object of type '<PlayFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayFeedback)))
  "Returns md5sum for a message object of type 'PlayFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayFeedback>)))
  "Returns full string definition for message of type '<PlayFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayFeedback)))
  "Returns full string definition for message of type 'PlayFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayFeedback
))
