; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PlayGoal.msg.html

(cl:defclass <PlayGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlayGoal (<PlayGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PlayGoal> is deprecated: use billiards_msgs-msg:PlayGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayGoal>) ostream)
  "Serializes a message object of type '<PlayGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayGoal>) istream)
  "Deserializes a message object of type '<PlayGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayGoal>)))
  "Returns string type for a message object of type '<PlayGoal>"
  "billiards_msgs/PlayGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayGoal)))
  "Returns string type for a message object of type 'PlayGoal"
  "billiards_msgs/PlayGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayGoal>)))
  "Returns md5sum for a message object of type '<PlayGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayGoal)))
  "Returns md5sum for a message object of type 'PlayGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayGoal>)))
  "Returns full string definition for message of type '<PlayGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayGoal)))
  "Returns full string definition for message of type 'PlayGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayGoal
))
