; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PoseStampedToTFFeedback.msg.html

(cl:defclass <PoseStampedToTFFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PoseStampedToTFFeedback (<PoseStampedToTFFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoseStampedToTFFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoseStampedToTFFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PoseStampedToTFFeedback> is deprecated: use billiards_msgs-msg:PoseStampedToTFFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoseStampedToTFFeedback>) ostream)
  "Serializes a message object of type '<PoseStampedToTFFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoseStampedToTFFeedback>) istream)
  "Deserializes a message object of type '<PoseStampedToTFFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoseStampedToTFFeedback>)))
  "Returns string type for a message object of type '<PoseStampedToTFFeedback>"
  "billiards_msgs/PoseStampedToTFFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoseStampedToTFFeedback)))
  "Returns string type for a message object of type 'PoseStampedToTFFeedback"
  "billiards_msgs/PoseStampedToTFFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoseStampedToTFFeedback>)))
  "Returns md5sum for a message object of type '<PoseStampedToTFFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoseStampedToTFFeedback)))
  "Returns md5sum for a message object of type 'PoseStampedToTFFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoseStampedToTFFeedback>)))
  "Returns full string definition for message of type '<PoseStampedToTFFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoseStampedToTFFeedback)))
  "Returns full string definition for message of type 'PoseStampedToTFFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoseStampedToTFFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoseStampedToTFFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PoseStampedToTFFeedback
))
