; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude PoseStampedToTFGoal.msg.html

(cl:defclass <PoseStampedToTFGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (child_frame
    :reader child_frame
    :initarg :child_frame
    :type cl:string
    :initform ""))
)

(cl:defclass PoseStampedToTFGoal (<PoseStampedToTFGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoseStampedToTFGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoseStampedToTFGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<PoseStampedToTFGoal> is deprecated: use billiards_msgs-msg:PoseStampedToTFGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <PoseStampedToTFGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader billiards_msgs-msg:pose-val is deprecated.  Use billiards_msgs-msg:pose instead.")
  (pose m))

(cl:ensure-generic-function 'child_frame-val :lambda-list '(m))
(cl:defmethod child_frame-val ((m <PoseStampedToTFGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader billiards_msgs-msg:child_frame-val is deprecated.  Use billiards_msgs-msg:child_frame instead.")
  (child_frame m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoseStampedToTFGoal>) ostream)
  "Serializes a message object of type '<PoseStampedToTFGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'child_frame))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'child_frame))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoseStampedToTFGoal>) istream)
  "Deserializes a message object of type '<PoseStampedToTFGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'child_frame) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'child_frame) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoseStampedToTFGoal>)))
  "Returns string type for a message object of type '<PoseStampedToTFGoal>"
  "billiards_msgs/PoseStampedToTFGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoseStampedToTFGoal)))
  "Returns string type for a message object of type 'PoseStampedToTFGoal"
  "billiards_msgs/PoseStampedToTFGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoseStampedToTFGoal>)))
  "Returns md5sum for a message object of type '<PoseStampedToTFGoal>"
  "ffb546346c53cf7343fc48bde3958c7b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoseStampedToTFGoal)))
  "Returns md5sum for a message object of type 'PoseStampedToTFGoal"
  "ffb546346c53cf7343fc48bde3958c7b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoseStampedToTFGoal>)))
  "Returns full string definition for message of type '<PoseStampedToTFGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped pose~%string child_frame~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoseStampedToTFGoal)))
  "Returns full string definition for message of type 'PoseStampedToTFGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped pose~%string child_frame~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoseStampedToTFGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
     4 (cl:length (cl:slot-value msg 'child_frame))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoseStampedToTFGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PoseStampedToTFGoal
    (cl:cons ':pose (pose msg))
    (cl:cons ':child_frame (child_frame msg))
))
