; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude StrikeFeedback.msg.html

(cl:defclass <StrikeFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StrikeFeedback (<StrikeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StrikeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StrikeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<StrikeFeedback> is deprecated: use billiards_msgs-msg:StrikeFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StrikeFeedback>) ostream)
  "Serializes a message object of type '<StrikeFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StrikeFeedback>) istream)
  "Deserializes a message object of type '<StrikeFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StrikeFeedback>)))
  "Returns string type for a message object of type '<StrikeFeedback>"
  "billiards_msgs/StrikeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StrikeFeedback)))
  "Returns string type for a message object of type 'StrikeFeedback"
  "billiards_msgs/StrikeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StrikeFeedback>)))
  "Returns md5sum for a message object of type '<StrikeFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StrikeFeedback)))
  "Returns md5sum for a message object of type 'StrikeFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StrikeFeedback>)))
  "Returns full string definition for message of type '<StrikeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StrikeFeedback)))
  "Returns full string definition for message of type 'StrikeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StrikeFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StrikeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StrikeFeedback
))
