; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude StrikeResult.msg.html

(cl:defclass <StrikeResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StrikeResult (<StrikeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StrikeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StrikeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<StrikeResult> is deprecated: use billiards_msgs-msg:StrikeResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StrikeResult>) ostream)
  "Serializes a message object of type '<StrikeResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StrikeResult>) istream)
  "Deserializes a message object of type '<StrikeResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StrikeResult>)))
  "Returns string type for a message object of type '<StrikeResult>"
  "billiards_msgs/StrikeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StrikeResult)))
  "Returns string type for a message object of type 'StrikeResult"
  "billiards_msgs/StrikeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StrikeResult>)))
  "Returns md5sum for a message object of type '<StrikeResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StrikeResult)))
  "Returns md5sum for a message object of type 'StrikeResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StrikeResult>)))
  "Returns full string definition for message of type '<StrikeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StrikeResult)))
  "Returns full string definition for message of type 'StrikeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StrikeResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StrikeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StrikeResult
))
