; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude StrikeGoal.msg.html

(cl:defclass <StrikeGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StrikeGoal (<StrikeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StrikeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StrikeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<StrikeGoal> is deprecated: use billiards_msgs-msg:StrikeGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StrikeGoal>) ostream)
  "Serializes a message object of type '<StrikeGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StrikeGoal>) istream)
  "Deserializes a message object of type '<StrikeGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StrikeGoal>)))
  "Returns string type for a message object of type '<StrikeGoal>"
  "billiards_msgs/StrikeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StrikeGoal)))
  "Returns string type for a message object of type 'StrikeGoal"
  "billiards_msgs/StrikeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StrikeGoal>)))
  "Returns md5sum for a message object of type '<StrikeGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StrikeGoal)))
  "Returns md5sum for a message object of type 'StrikeGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StrikeGoal>)))
  "Returns full string definition for message of type '<StrikeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StrikeGoal)))
  "Returns full string definition for message of type 'StrikeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StrikeGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StrikeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StrikeGoal
))
