; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude SwingArmsGoal.msg.html

(cl:defclass <SwingArmsGoal> (roslisp-msg-protocol:ros-message)
  ((away
    :reader away
    :initarg :away
    :type cl:boolean
    :initform cl:nil)
   (initial_wait
    :reader initial_wait
    :initarg :initial_wait
    :type cl:real
    :initform 0))
)

(cl:defclass SwingArmsGoal (<SwingArmsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SwingArmsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SwingArmsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<SwingArmsGoal> is deprecated: use billiards_msgs-msg:SwingArmsGoal instead.")))

(cl:ensure-generic-function 'away-val :lambda-list '(m))
(cl:defmethod away-val ((m <SwingArmsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader billiards_msgs-msg:away-val is deprecated.  Use billiards_msgs-msg:away instead.")
  (away m))

(cl:ensure-generic-function 'initial_wait-val :lambda-list '(m))
(cl:defmethod initial_wait-val ((m <SwingArmsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader billiards_msgs-msg:initial_wait-val is deprecated.  Use billiards_msgs-msg:initial_wait instead.")
  (initial_wait m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SwingArmsGoal>) ostream)
  "Serializes a message object of type '<SwingArmsGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'away) 1 0)) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'initial_wait)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'initial_wait) (cl:floor (cl:slot-value msg 'initial_wait)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SwingArmsGoal>) istream)
  "Deserializes a message object of type '<SwingArmsGoal>"
    (cl:setf (cl:slot-value msg 'away) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'initial_wait) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SwingArmsGoal>)))
  "Returns string type for a message object of type '<SwingArmsGoal>"
  "billiards_msgs/SwingArmsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SwingArmsGoal)))
  "Returns string type for a message object of type 'SwingArmsGoal"
  "billiards_msgs/SwingArmsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SwingArmsGoal>)))
  "Returns md5sum for a message object of type '<SwingArmsGoal>"
  "1438bf444bf9625d8bf525b924322cd8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SwingArmsGoal)))
  "Returns md5sum for a message object of type 'SwingArmsGoal"
  "1438bf444bf9625d8bf525b924322cd8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SwingArmsGoal>)))
  "Returns full string definition for message of type '<SwingArmsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool away~%duration initial_wait~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SwingArmsGoal)))
  "Returns full string definition for message of type 'SwingArmsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool away~%duration initial_wait~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SwingArmsGoal>))
  (cl:+ 0
     1
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SwingArmsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SwingArmsGoal
    (cl:cons ':away (away msg))
    (cl:cons ':initial_wait (initial_wait msg))
))
