; Auto-generated. Do not edit!


(cl:in-package billiards_msgs-msg)


;//! \htmlinclude SwingArmsFeedback.msg.html

(cl:defclass <SwingArmsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SwingArmsFeedback (<SwingArmsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SwingArmsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SwingArmsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name billiards_msgs-msg:<SwingArmsFeedback> is deprecated: use billiards_msgs-msg:SwingArmsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SwingArmsFeedback>) ostream)
  "Serializes a message object of type '<SwingArmsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SwingArmsFeedback>) istream)
  "Deserializes a message object of type '<SwingArmsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SwingArmsFeedback>)))
  "Returns string type for a message object of type '<SwingArmsFeedback>"
  "billiards_msgs/SwingArmsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SwingArmsFeedback)))
  "Returns string type for a message object of type 'SwingArmsFeedback"
  "billiards_msgs/SwingArmsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SwingArmsFeedback>)))
  "Returns md5sum for a message object of type '<SwingArmsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SwingArmsFeedback)))
  "Returns md5sum for a message object of type 'SwingArmsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SwingArmsFeedback>)))
  "Returns full string definition for message of type '<SwingArmsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SwingArmsFeedback)))
  "Returns full string definition for message of type 'SwingArmsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SwingArmsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SwingArmsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SwingArmsFeedback
))
