/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/BallState.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_BALLSTATE_H
#define BILLIARDS_MSGS_MESSAGE_BALLSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PointStamped.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct BallState_ {
  typedef BallState_<ContainerAllocator> Type;

  BallState_()
  : id(0)
  , pocketed(false)
  , point()
  , group_id(0)
  {
  }

  BallState_(const ContainerAllocator& _alloc)
  : id(0)
  , pocketed(false)
  , point(_alloc)
  , group_id(0)
  {
  }

  typedef int8_t _id_type;
  int8_t id;

  typedef uint8_t _pocketed_type;
  uint8_t pocketed;

  typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _point_type;
   ::geometry_msgs::PointStamped_<ContainerAllocator>  point;

  typedef int8_t _group_id_type;
  int8_t group_id;


  typedef boost::shared_ptr< ::billiards_msgs::BallState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::BallState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BallState
typedef  ::billiards_msgs::BallState_<std::allocator<void> > BallState;

typedef boost::shared_ptr< ::billiards_msgs::BallState> BallStatePtr;
typedef boost::shared_ptr< ::billiards_msgs::BallState const> BallStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::BallState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::BallState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::BallState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::BallState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::BallState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6ea21e2ed6a05165e2c5d45298536113";
  }

  static const char* value(const  ::billiards_msgs::BallState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6ea21e2ed6a05165ULL;
  static const uint64_t static_value2 = 0xe2c5d45298536113ULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::BallState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/BallState";
  }

  static const char* value(const  ::billiards_msgs::BallState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::BallState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8                  id                  # id of the ball\n\
                                          # 0-cue ball, 1-15 for each of the 15 balls\n\
bool                  pocketed            # false if ball is on the table\n\
geometry_msgs/PointStamped   point        # location of each ball\n\
int8                  group_id            # if we want to group the ball\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::BallState_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::BallState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.pocketed);
    stream.next(m.point);
    stream.next(m.group_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BallState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::BallState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::BallState_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pocketed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pocketed);
    s << indent << "point: ";
s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "group_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.group_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_BALLSTATE_H

