/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/GetTableStateActionGoal.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_GETTABLESTATEACTIONGOAL_H
#define BILLIARDS_MSGS_MESSAGE_GETTABLESTATEACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "billiards_msgs/GetTableStateGoal.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct GetTableStateActionGoal_ {
  typedef GetTableStateActionGoal_<ContainerAllocator> Type;

  GetTableStateActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  GetTableStateActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::billiards_msgs::GetTableStateGoal_<ContainerAllocator>  _goal_type;
   ::billiards_msgs::GetTableStateGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetTableStateActionGoal
typedef  ::billiards_msgs::GetTableStateActionGoal_<std::allocator<void> > GetTableStateActionGoal;

typedef boost::shared_ptr< ::billiards_msgs::GetTableStateActionGoal> GetTableStateActionGoalPtr;
typedef boost::shared_ptr< ::billiards_msgs::GetTableStateActionGoal const> GetTableStateActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "79109d6e28db44dcd3c6a510eac023e9";
  }

  static const char* value(const  ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x79109d6e28db44dcULL;
  static const uint64_t static_value2 = 0xd3c6a510eac023e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/GetTableStateActionGoal";
  }

  static const char* value(const  ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
GetTableStateGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: billiards_msgs/GetTableStateGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string table_frame_id\n\
bool filter_against_table\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetTableStateActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::GetTableStateActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::billiards_msgs::GetTableStateGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_GETTABLESTATEACTIONGOAL_H

