/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/LocalizeTableResult.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_LOCALIZETABLERESULT_H
#define BILLIARDS_MSGS_MESSAGE_LOCALIZETABLERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct LocalizeTableResult_ {
  typedef LocalizeTableResult_<ContainerAllocator> Type;

  LocalizeTableResult_()
  : pose()
  , child_frame()
  {
  }

  LocalizeTableResult_(const ContainerAllocator& _alloc)
  : pose(_alloc)
  , child_frame(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  pose;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _child_frame_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  child_frame;


  typedef boost::shared_ptr< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalizeTableResult
typedef  ::billiards_msgs::LocalizeTableResult_<std::allocator<void> > LocalizeTableResult;

typedef boost::shared_ptr< ::billiards_msgs::LocalizeTableResult> LocalizeTableResultPtr;
typedef boost::shared_ptr< ::billiards_msgs::LocalizeTableResult const> LocalizeTableResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ffb546346c53cf7343fc48bde3958c7b";
  }

  static const char* value(const  ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xffb546346c53cf73ULL;
  static const uint64_t static_value2 = 0x43fc48bde3958c7bULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/LocalizeTableResult";
  }

  static const char* value(const  ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
geometry_msgs/PoseStamped pose\n\
string child_frame\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pose);
    stream.next(m.child_frame);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalizeTableResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::LocalizeTableResult_<ContainerAllocator> & v) 
  {
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "child_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.child_frame);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_LOCALIZETABLERESULT_H

