/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/PlaceBridgeAction.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEACTION_H
#define BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "billiards_msgs/PlaceBridgeActionGoal.h"
#include "billiards_msgs/PlaceBridgeActionResult.h"
#include "billiards_msgs/PlaceBridgeActionFeedback.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct PlaceBridgeAction_ {
  typedef PlaceBridgeAction_<ContainerAllocator> Type;

  PlaceBridgeAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  PlaceBridgeAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::billiards_msgs::PlaceBridgeActionGoal_<ContainerAllocator>  _action_goal_type;
   ::billiards_msgs::PlaceBridgeActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::billiards_msgs::PlaceBridgeActionResult_<ContainerAllocator>  _action_result_type;
   ::billiards_msgs::PlaceBridgeActionResult_<ContainerAllocator>  action_result;

  typedef  ::billiards_msgs::PlaceBridgeActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::billiards_msgs::PlaceBridgeActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlaceBridgeAction
typedef  ::billiards_msgs::PlaceBridgeAction_<std::allocator<void> > PlaceBridgeAction;

typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeAction> PlaceBridgeActionPtr;
typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeAction const> PlaceBridgeActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "de990ba2b975e268eb0b33744b702252";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xde990ba2b975e268ULL;
  static const uint64_t static_value2 = 0xeb0b33744b702252ULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/PlaceBridgeAction";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
PlaceBridgeActionGoal action_goal\n\
PlaceBridgeActionResult action_result\n\
PlaceBridgeActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
PlaceBridgeGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool down\n\
geometry_msgs/PoseStamped pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
PlaceBridgeResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
PlaceBridgeFeedback feedback\n\
\n\
================================================================================\n\
MSG: billiards_msgs/PlaceBridgeFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlaceBridgeAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::PlaceBridgeAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::billiards_msgs::PlaceBridgeActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::billiards_msgs::PlaceBridgeActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::billiards_msgs::PlaceBridgeActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEACTION_H

