/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/PlaceBridgeGoal.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEGOAL_H
#define BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct PlaceBridgeGoal_ {
  typedef PlaceBridgeGoal_<ContainerAllocator> Type;

  PlaceBridgeGoal_()
  : down(false)
  , pose()
  {
  }

  PlaceBridgeGoal_(const ContainerAllocator& _alloc)
  : down(false)
  , pose(_alloc)
  {
  }

  typedef uint8_t _down_type;
  uint8_t down;

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  pose;


  typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlaceBridgeGoal
typedef  ::billiards_msgs::PlaceBridgeGoal_<std::allocator<void> > PlaceBridgeGoal;

typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeGoal> PlaceBridgeGoalPtr;
typedef boost::shared_ptr< ::billiards_msgs::PlaceBridgeGoal const> PlaceBridgeGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eb0ebaa46030099569244fecb945e17e";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeb0ebaa460300995ULL;
  static const uint64_t static_value2 = 0x69244fecb945e17eULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/PlaceBridgeGoal";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool down\n\
geometry_msgs/PoseStamped pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.down);
    stream.next(m.pose);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlaceBridgeGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::PlaceBridgeGoal_<ContainerAllocator> & v) 
  {
    s << indent << "down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.down);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_PLACEBRIDGEGOAL_H

