/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/PlanShotResult.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_PLANSHOTRESULT_H
#define BILLIARDS_MSGS_MESSAGE_PLANSHOTRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "billiards_msgs/ShotPlan.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct PlanShotResult_ {
  typedef PlanShotResult_<ContainerAllocator> Type;

  PlanShotResult_()
  : shot()
  {
  }

  PlanShotResult_(const ContainerAllocator& _alloc)
  : shot(_alloc)
  {
  }

  typedef  ::billiards_msgs::ShotPlan_<ContainerAllocator>  _shot_type;
   ::billiards_msgs::ShotPlan_<ContainerAllocator>  shot;


  typedef boost::shared_ptr< ::billiards_msgs::PlanShotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::PlanShotResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlanShotResult
typedef  ::billiards_msgs::PlanShotResult_<std::allocator<void> > PlanShotResult;

typedef boost::shared_ptr< ::billiards_msgs::PlanShotResult> PlanShotResultPtr;
typedef boost::shared_ptr< ::billiards_msgs::PlanShotResult const> PlanShotResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::PlanShotResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::PlanShotResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlanShotResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlanShotResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::PlanShotResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dc03f55e8465fc664d92eb4eb351849e";
  }

  static const char* value(const  ::billiards_msgs::PlanShotResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdc03f55e8465fc66ULL;
  static const uint64_t static_value2 = 0x4d92eb4eb351849eULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::PlanShotResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/PlanShotResult";
  }

  static const char* value(const  ::billiards_msgs::PlanShotResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::PlanShotResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
ShotPlan shot\n\
\n\
================================================================================\n\
MSG: billiards_msgs/ShotPlan\n\
# describes plan for a single shot\n\
BallState ball\n\
geometry_msgs/PoseStamped base_pose                     # where PR2 should \"stand\"\n\
geometry_msgs/PoseStamped bridge_pose                   # where to put the bridge\n\
                                                        # orientation is: x-forward (towards cue ball)\n\
                                                        #                 z-(up)\n\
                                                        #                 y-robot left\n\
float64                   velocity                      # not used for now\n\
\n\
\n\
================================================================================\n\
MSG: billiards_msgs/BallState\n\
int8                  id                  # id of the ball\n\
                                          # 0-cue ball, 1-15 for each of the 15 balls\n\
bool                  pocketed            # false if ball is on the table\n\
geometry_msgs/PointStamped   point        # location of each ball\n\
int8                  group_id            # if we want to group the ball\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::PlanShotResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::PlanShotResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.shot);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlanShotResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::PlanShotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::PlanShotResult_<ContainerAllocator> & v) 
  {
    s << indent << "shot: ";
s << std::endl;
    Printer< ::billiards_msgs::ShotPlan_<ContainerAllocator> >::stream(s, indent + "  ", v.shot);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_PLANSHOTRESULT_H

