/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/PlayGoal.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_PLAYGOAL_H
#define BILLIARDS_MSGS_MESSAGE_PLAYGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace billiards_msgs
{
template <class ContainerAllocator>
struct PlayGoal_ {
  typedef PlayGoal_<ContainerAllocator> Type;

  PlayGoal_()
  {
  }

  PlayGoal_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::billiards_msgs::PlayGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::PlayGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlayGoal
typedef  ::billiards_msgs::PlayGoal_<std::allocator<void> > PlayGoal;

typedef boost::shared_ptr< ::billiards_msgs::PlayGoal> PlayGoalPtr;
typedef boost::shared_ptr< ::billiards_msgs::PlayGoal const> PlayGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::PlayGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::PlayGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlayGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PlayGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::PlayGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::billiards_msgs::PlayGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::PlayGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/PlayGoal";
  }

  static const char* value(const  ::billiards_msgs::PlayGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::PlayGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::PlayGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::billiards_msgs::PlayGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::PlayGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlayGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::PlayGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::PlayGoal_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_PLAYGOAL_H

