/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/PocketState.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_POCKETSTATE_H
#define BILLIARDS_MSGS_MESSAGE_POCKETSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PointStamped.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct PocketState_ {
  typedef PocketState_<ContainerAllocator> Type;

  PocketState_()
  : id(0)
  , point()
  {
  }

  PocketState_(const ContainerAllocator& _alloc)
  : id(0)
  , point(_alloc)
  {
  }

  typedef uint8_t _id_type;
  uint8_t id;

  typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _point_type;
   ::geometry_msgs::PointStamped_<ContainerAllocator>  point;


  typedef boost::shared_ptr< ::billiards_msgs::PocketState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::PocketState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PocketState
typedef  ::billiards_msgs::PocketState_<std::allocator<void> > PocketState;

typedef boost::shared_ptr< ::billiards_msgs::PocketState> PocketStatePtr;
typedef boost::shared_ptr< ::billiards_msgs::PocketState const> PocketStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::PocketState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::PocketState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PocketState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::PocketState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::PocketState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b23912eba03767ebfc2e9b41ef37053d";
  }

  static const char* value(const  ::billiards_msgs::PocketState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb23912eba03767ebULL;
  static const uint64_t static_value2 = 0xfc2e9b41ef37053dULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::PocketState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/PocketState";
  }

  static const char* value(const  ::billiards_msgs::PocketState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::PocketState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8                 id              # pocket id, see wiki for picture\n\
geometry_msgs/PointStamped   point    # point of the pocket to aim for,\n\
                                      # target ball trajectory should\n\
                                      # cross this point if shot is successful\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::PocketState_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::PocketState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.point);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PocketState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::PocketState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::PocketState_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "point: ";
s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_POCKETSTATE_H

