/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/SwingArmsGoal.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_SWINGARMSGOAL_H
#define BILLIARDS_MSGS_MESSAGE_SWINGARMSGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace billiards_msgs
{
template <class ContainerAllocator>
struct SwingArmsGoal_ {
  typedef SwingArmsGoal_<ContainerAllocator> Type;

  SwingArmsGoal_()
  : away(false)
  , initial_wait()
  {
  }

  SwingArmsGoal_(const ContainerAllocator& _alloc)
  : away(false)
  , initial_wait()
  {
  }

  typedef uint8_t _away_type;
  uint8_t away;

  typedef ros::Duration _initial_wait_type;
  ros::Duration initial_wait;


  typedef boost::shared_ptr< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SwingArmsGoal
typedef  ::billiards_msgs::SwingArmsGoal_<std::allocator<void> > SwingArmsGoal;

typedef boost::shared_ptr< ::billiards_msgs::SwingArmsGoal> SwingArmsGoalPtr;
typedef boost::shared_ptr< ::billiards_msgs::SwingArmsGoal const> SwingArmsGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1438bf444bf9625d8bf525b924322cd8";
  }

  static const char* value(const  ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1438bf444bf9625dULL;
  static const uint64_t static_value2 = 0x8bf525b924322cd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/SwingArmsGoal";
  }

  static const char* value(const  ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool away\n\
duration initial_wait\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.away);
    stream.next(m.initial_wait);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SwingArmsGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::SwingArmsGoal_<ContainerAllocator> & v) 
  {
    s << indent << "away: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.away);
    s << indent << "initial_wait: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.initial_wait);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_SWINGARMSGOAL_H

