/* Auto-generated by genmsg_cpp for file /home/ashok/Projects/billiards/billiards_msgs/msg/TableState.msg */
#ifndef BILLIARDS_MSGS_MESSAGE_TABLESTATE_H
#define BILLIARDS_MSGS_MESSAGE_TABLESTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "billiards_msgs/BallState.h"

namespace billiards_msgs
{
template <class ContainerAllocator>
struct TableState_ {
  typedef TableState_<ContainerAllocator> Type;

  TableState_()
  : balls()
  {
  }

  TableState_(const ContainerAllocator& _alloc)
  : balls(_alloc)
  {
  }

  typedef std::vector< ::billiards_msgs::BallState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::billiards_msgs::BallState_<ContainerAllocator> >::other >  _balls_type;
  std::vector< ::billiards_msgs::BallState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::billiards_msgs::BallState_<ContainerAllocator> >::other >  balls;


  typedef boost::shared_ptr< ::billiards_msgs::TableState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::billiards_msgs::TableState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TableState
typedef  ::billiards_msgs::TableState_<std::allocator<void> > TableState;

typedef boost::shared_ptr< ::billiards_msgs::TableState> TableStatePtr;
typedef boost::shared_ptr< ::billiards_msgs::TableState const> TableStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::billiards_msgs::TableState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::billiards_msgs::TableState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace billiards_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::TableState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::billiards_msgs::TableState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::billiards_msgs::TableState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "495f61486cf3780b332ac6537332d69a";
  }

  static const char* value(const  ::billiards_msgs::TableState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x495f61486cf3780bULL;
  static const uint64_t static_value2 = 0x332ac6537332d69aULL;
};

template<class ContainerAllocator>
struct DataType< ::billiards_msgs::TableState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "billiards_msgs/TableState";
  }

  static const char* value(const  ::billiards_msgs::TableState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::billiards_msgs::TableState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "BallState[] balls\n\
\n\
================================================================================\n\
MSG: billiards_msgs/BallState\n\
int8                  id                  # id of the ball\n\
                                          # 0-cue ball, 1-15 for each of the 15 balls\n\
bool                  pocketed            # false if ball is on the table\n\
geometry_msgs/PointStamped   point        # location of each ball\n\
int8                  group_id            # if we want to group the ball\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::billiards_msgs::TableState_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::billiards_msgs::TableState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.balls);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TableState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::billiards_msgs::TableState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::billiards_msgs::TableState_<ContainerAllocator> & v) 
  {
    s << indent << "balls[]" << std::endl;
    for (size_t i = 0; i < v.balls.size(); ++i)
    {
      s << indent << "  balls[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::billiards_msgs::BallState_<ContainerAllocator> >::stream(s, indent + "    ", v.balls[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // BILLIARDS_MSGS_MESSAGE_TABLESTATE_H

